apm install minimap
apm install atom-beautify
apm install file-icons
apm nstall pigments
apm install editorconfig
apm install todo-show
apm install highlight-selected
apm install pandoc
apm install rst-preview-pandoc
apm install markdown-preview-pandoc
apm install linter-htmlhint
apm install linter-jshint
apm install javascript-snippets
apm install seti-ui
apm install atom-material-ui
